- name: Configure backend
  hosts: backend
  become: yes
  tasks:
  - name: Disable nodejs version
    ansible.builtin.command: dnf module disable nodejs -y
  
  - name: Enable nodejs version 20
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: Install Nodejs and npm
    dnf:
      name: nodejs
      state: present