- name: Intsall MySQL server and configuration
  hosts: mysql
  become: yes
  tasks:
  - name: Install Mysql server
    ansible.builtlin.package:
      name: mysql-server
      state: installed
  - name: start and enable mysql server
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes
  #Setting up user and password
  - name: connect to mysql server
    community.mysql.mysql_info:
      login_user: root
      login_password: ExpenseApp@1
      login_host: 172.31.20.18
    register: mysql_info
  #Print the output
  - name:
    ansible.builtin.debug:
      msg: "{{ mysql_info }}"