- name: Intsall MySQL server and configuration
  hosts: mysql
  become: yes
  tasks:
  - name: Install Mysql server
    ansible.buitln.packge:
      name: mysql-server
      state: installed
  - name: start and enable mysql server
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes
  
  #Setting up password
  - name: Connect to myusql server
    
